create database customer_pattern;

use customer_pattern;
show tables;
select * from customer;

ALTER TABLE customer RENAME COLUMN `purchase_amount_(usd)` TO purchased_amount;
-- 1. WHAT IS THE TOTAL REVENUWE GENERATED BY MALE V/S FEMALE CUSTOMERS? 

SELECT gender, SUM(purchased_amount) AS REVENUE
FROM customer
group by gender;

-- 2. WHICH CUSTOMER USED A DISCOUNT BUT STLL SPENT MORE THAN THA AVERAGE PURCHASE AMOOUNT?
select customer_id, purchased_amount
from customer
where discount_applied = 'Yes' and purchased_amount >= (select avg(purchased_amount)
						   from customer);

-- 3. WHICH ARE THE TOP 5 PRODUCTS WITH HIGHEST AVERAGE REVIEW RATING?

select item_purchased, round(avg(review_rating),2) as avg_rating
from customer
group by item_purchased
order by avg_rating desc
limit 5;

-- 4. COMPARE THE AVERAGE PURCHASE AMOUNT B/W STANDARD AND EXPRESS SHIPPING to find on which shipping type company should focus more.

select shipping_type , round(avg(purchased_amount),2) as avg_purchase_amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type; 

-- 5. DO SUBSCRIBED CUSTOMERS SPEND MORE? COMPARE AVERAGE SPEND AND TOTAL REVENUE B/W  SUBSCRIBED AND NON-SUBSCRIBED CUSTOMERS

select subscription_status, 
count(customer_id) as total_customer, 
round(avg(purchased_amount),2) as avg_spend,
round(sum(purchased_amount),2) as revenue
from customer
group by subscription_status
order by revenue, avg_spend desc;

-- 6. WHICH 5 PRODUCTS HAVE THE HIGHEST PERCENTAGE OF PURCHASE WITH DISCOUNTS APPLIED?

select item_purchased, 
round(sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*) * 100 ,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- 7 SEGMENT CUSTOMERS INTO NEW, RETURNING, AND LOYAL BASED ON THEIR TOTAL NUMBER OF PREVIOUS PURCHASES AND SHOW THE COUNT OF EACH SEGMENT?

WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases, 
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal' 
        END AS Customer_Segment
    FROM customer
)                
SELECT 
    Customer_Segment, 
    COUNT(*) AS "Number of customers" 
FROM customer_type                     
GROUP BY Customer_Segment;

-- 8. WHAT ARE THE TOP 3 MOST PURCHASED PRODUCTS WITHIIN EACH CATEGORY? 

with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased 
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- 9. ARE CUSTOMERS WHO ARE REPEAT BUYERS (MORE THAN 5 PREVIOUS PURCHASES) ALSO LIKELY TO SUBSCRIBE? 

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status;

-- 10. WHAT SI THE REVENUE CONTIBUTED OF EACH AGE GROUP? 
select age_group,
sum(purchased_amount) as revenue
from customer
group by age_group
order by revenue desc;